-- ===========================================
-- SmartEngine core tables - PostgreSQL HASH partitioned version
-- All IDs generated by application-layer SnowflakeIdGenerator
-- se_deployment_instance is NOT partitioned and NOT included here
-- ===========================================

-- ===========================================
-- Process instance table (root table)
-- Partition key: id (PK remains single-column id)
-- ===========================================
CREATE TABLE se_process_instance (
  id bigint NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_definition_id_and_version varchar(128) NOT NULL,
  process_definition_type varchar(255),
  status varchar(64) NOT NULL,
  parent_process_instance_id bigint,
  parent_execution_instance_id bigint,
  start_user_id varchar(128),
  biz_unique_id varchar(255),
  reason varchar(255),
  comment varchar(255),
  title varchar(255),
  tag varchar(255),
  complete_time timestamp(6),
  tenant_id varchar(64),
  PRIMARY KEY (id)
) PARTITION BY HASH (id);

COMMENT ON TABLE se_process_instance IS 'Process instance table';
COMMENT ON COLUMN se_process_instance.status IS '1.running 2.completed 3.aborted';
COMMENT ON COLUMN se_process_instance.complete_time IS 'process completion time';

CREATE TABLE se_process_instance_p00 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE se_process_instance_p01 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE se_process_instance_p02 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE se_process_instance_p03 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE se_process_instance_p04 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE se_process_instance_p05 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE se_process_instance_p06 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE se_process_instance_p07 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE se_process_instance_p08 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE se_process_instance_p09 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE se_process_instance_p10 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE se_process_instance_p11 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE se_process_instance_p12 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE se_process_instance_p13 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE se_process_instance_p14 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE se_process_instance_p15 PARTITION OF se_process_instance FOR VALUES WITH (MODULUS 16, REMAINDER 15);

-- ===========================================
-- Activity instance table
-- Partition key: process_instance_id
-- PK: (id, process_instance_id)
-- ===========================================
CREATE TABLE se_activity_instance (
  id bigint NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  process_definition_id_and_version varchar(255) NOT NULL,
  process_definition_activity_id varchar(64) NOT NULL,
  tenant_id varchar(64),
  PRIMARY KEY (id, process_instance_id)
) PARTITION BY HASH (process_instance_id);

COMMENT ON TABLE se_activity_instance IS 'Activity instance table';

CREATE TABLE se_activity_instance_p00 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE se_activity_instance_p01 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE se_activity_instance_p02 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE se_activity_instance_p03 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE se_activity_instance_p04 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE se_activity_instance_p05 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE se_activity_instance_p06 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE se_activity_instance_p07 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE se_activity_instance_p08 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE se_activity_instance_p09 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE se_activity_instance_p10 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE se_activity_instance_p11 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE se_activity_instance_p12 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE se_activity_instance_p13 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE se_activity_instance_p14 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE se_activity_instance_p15 PARTITION OF se_activity_instance FOR VALUES WITH (MODULUS 16, REMAINDER 15);

-- ===========================================
-- Execution instance table
-- Partition key: process_instance_id
-- PK: (id, process_instance_id)
-- ===========================================
CREATE TABLE se_execution_instance (
  id bigint NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  process_definition_id_and_version varchar(255) NOT NULL,
  process_definition_activity_id varchar(255) NOT NULL,
  activity_instance_id bigint NOT NULL,
  block_id bigint,
  active smallint NOT NULL,
  tenant_id varchar(64),
  PRIMARY KEY (id, process_instance_id)
) PARTITION BY HASH (process_instance_id);

COMMENT ON TABLE se_execution_instance IS 'Execution instance table';
COMMENT ON COLUMN se_execution_instance.active IS '1:active 0:inactive';

CREATE TABLE se_execution_instance_p00 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE se_execution_instance_p01 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE se_execution_instance_p02 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE se_execution_instance_p03 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE se_execution_instance_p04 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE se_execution_instance_p05 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE se_execution_instance_p06 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE se_execution_instance_p07 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE se_execution_instance_p08 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE se_execution_instance_p09 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE se_execution_instance_p10 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE se_execution_instance_p11 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE se_execution_instance_p12 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE se_execution_instance_p13 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE se_execution_instance_p14 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE se_execution_instance_p15 PARTITION OF se_execution_instance FOR VALUES WITH (MODULUS 16, REMAINDER 15);

-- ===========================================
-- Task instance table
-- Partition key: process_instance_id
-- PK: (id, process_instance_id)
-- ===========================================
CREATE TABLE se_task_instance (
  id bigint NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  process_definition_id_and_version varchar(128),
  process_definition_type varchar(255),
  activity_instance_id bigint NOT NULL,
  process_definition_activity_id varchar(255) NOT NULL,
  execution_instance_id bigint NOT NULL,
  claim_user_id varchar(255),
  title varchar(255),
  priority int DEFAULT 500,
  tag varchar(255),
  claim_time timestamp(6),
  complete_time timestamp(6),
  status varchar(255) NOT NULL,
  comment varchar(255),
  extension varchar(255),
  domain_code varchar(64) DEFAULT NULL,
  extra jsonb DEFAULT NULL,
  tenant_id varchar(64),
  PRIMARY KEY (id, process_instance_id)
) PARTITION BY HASH (process_instance_id);

COMMENT ON TABLE se_task_instance IS 'Task instance table';

CREATE TABLE se_task_instance_p00 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE se_task_instance_p01 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE se_task_instance_p02 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE se_task_instance_p03 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE se_task_instance_p04 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE se_task_instance_p05 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE se_task_instance_p06 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE se_task_instance_p07 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE se_task_instance_p08 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE se_task_instance_p09 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE se_task_instance_p10 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE se_task_instance_p11 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE se_task_instance_p12 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE se_task_instance_p13 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE se_task_instance_p14 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE se_task_instance_p15 PARTITION OF se_task_instance FOR VALUES WITH (MODULUS 16, REMAINDER 15);

-- ===========================================
-- Task assignee instance table
-- Partition key: process_instance_id
-- PK: (id, process_instance_id)
-- ===========================================
CREATE TABLE se_task_assignee_instance (
  id bigint NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  task_instance_id bigint NOT NULL,
  assignee_id varchar(255) NOT NULL,
  assignee_type varchar(128) NOT NULL,
  tenant_id varchar(64),
  PRIMARY KEY (id, process_instance_id)
) PARTITION BY HASH (process_instance_id);

COMMENT ON TABLE se_task_assignee_instance IS 'Task assignee instance table';

CREATE TABLE se_task_assignee_instance_p00 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE se_task_assignee_instance_p01 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE se_task_assignee_instance_p02 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE se_task_assignee_instance_p03 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE se_task_assignee_instance_p04 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE se_task_assignee_instance_p05 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE se_task_assignee_instance_p06 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE se_task_assignee_instance_p07 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE se_task_assignee_instance_p08 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE se_task_assignee_instance_p09 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE se_task_assignee_instance_p10 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE se_task_assignee_instance_p11 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE se_task_assignee_instance_p12 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE se_task_assignee_instance_p13 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE se_task_assignee_instance_p14 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE se_task_assignee_instance_p15 PARTITION OF se_task_assignee_instance FOR VALUES WITH (MODULUS 16, REMAINDER 15);

-- ===========================================
-- Variable instance table
-- Partition key: process_instance_id
-- PK: (id, process_instance_id)
-- ===========================================
CREATE TABLE se_variable_instance (
  id bigint NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  execution_instance_id bigint,
  field_key varchar(128) NOT NULL,
  field_type varchar(128) NOT NULL,
  field_double_value decimal(65,30),
  field_long_value bigint,
  field_string_value varchar(4000),
  tenant_id varchar(64),
  PRIMARY KEY (id, process_instance_id)
) PARTITION BY HASH (process_instance_id);

COMMENT ON TABLE se_variable_instance IS 'Variable instance table';

CREATE TABLE se_variable_instance_p00 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE se_variable_instance_p01 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE se_variable_instance_p02 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE se_variable_instance_p03 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE se_variable_instance_p04 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE se_variable_instance_p05 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE se_variable_instance_p06 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE se_variable_instance_p07 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE se_variable_instance_p08 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE se_variable_instance_p09 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE se_variable_instance_p10 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE se_variable_instance_p11 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE se_variable_instance_p12 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE se_variable_instance_p13 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE se_variable_instance_p14 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE se_variable_instance_p15 PARTITION OF se_variable_instance FOR VALUES WITH (MODULUS 16, REMAINDER 15);
