package com.alibaba.smart.framework.engine.dialect;

/**
 * Enumeration of ID generation strategies supported by different databases.
 *
 * @author SmartEngine Team
 */
public enum IdGenerationType {

    /**
     * Auto-increment column (MySQL, H2, SQLite, OceanBase)
     */
    AUTO_INCREMENT,

    /**
     * Identity column (PostgreSQL, SQL Server, 达梦, 人大金仓)
     */
    IDENTITY,

    /**
     * Sequence (Oracle)
     */
    SEQUENCE,

    /**
     * UUID generated by application
     */
    UUID,

    /**
     * Custom ID generator (e.g., Snowflake)
     */
    CUSTOM
}
