-- Create user task index table and user notification index table (PostgreSQL version)
-- These tables support fast user-centric queries in sharding mode

-- ===========================================
-- User task index table (not partitioned)
-- Stores only active/pending tasks for fast user-centric queries
-- ===========================================
CREATE TABLE IF NOT EXISTS se_user_task_index (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id varchar(64),
  assignee_id varchar(255) NOT NULL,
  assignee_type varchar(128) NOT NULL DEFAULT 'user',
  task_instance_id bigint NOT NULL,
  process_instance_id bigint NOT NULL,
  process_definition_type varchar(255),
  domain_code varchar(64),
  extra jsonb,
  task_status varchar(64) NOT NULL,
  task_gmt_modified timestamp(6),
  title varchar(255),
  priority int DEFAULT 500,
  PRIMARY KEY (id)
);

-- Unique constraint for deduplication
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_task_idx
  ON se_user_task_index (tenant_id, assignee_id, task_instance_id);

-- Full index for general status queries
CREATE INDEX IF NOT EXISTS idx_user_task_status
  ON se_user_task_index (tenant_id, assignee_id, assignee_type, task_status);

-- Partial index for pending tasks only (most frequent query)
CREATE INDEX IF NOT EXISTS idx_user_task_pending
  ON se_user_task_index (tenant_id, assignee_id, assignee_type, task_status)
  WHERE task_status = 'pending';

-- Index for process definition type queries
CREATE INDEX IF NOT EXISTS idx_user_task_type
  ON se_user_task_index (tenant_id, assignee_id, process_definition_type, task_status);

COMMENT ON TABLE se_user_task_index IS 'User task index for sharding mode';

-- ===========================================
-- User notification index table (not partitioned)
-- Stores only unread notifications for fast user-centric queries
-- ===========================================
CREATE TABLE IF NOT EXISTS se_user_notification_index (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id varchar(64),
  receiver_user_id varchar(255) NOT NULL,
  notification_id bigint NOT NULL,
  process_instance_id bigint NOT NULL,
  notification_type varchar(64) NOT NULL,
  title varchar(255),
  read_status varchar(64) NOT NULL DEFAULT 'unread',
  gmt_create timestamp(6) NOT NULL,
  PRIMARY KEY (id)
);

-- Unique constraint for deduplication
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_notif_idx
  ON se_user_notification_index (tenant_id, receiver_user_id, notification_id);

-- Full index for receiver queries
CREATE INDEX IF NOT EXISTS idx_user_notif_receiver
  ON se_user_notification_index (tenant_id, receiver_user_id, read_status);

-- Partial index for unread notifications only (most frequent query)
CREATE INDEX IF NOT EXISTS idx_user_notif_unread
  ON se_user_notification_index (tenant_id, receiver_user_id, read_status)
  WHERE read_status = 'unread';

-- Index for notification type queries
CREATE INDEX IF NOT EXISTS idx_user_notif_type
  ON se_user_notification_index (tenant_id, receiver_user_id, notification_type, read_status);

COMMENT ON TABLE se_user_notification_index IS 'User notification index for sharding mode';
