package com.alibaba.smart.framework.engine.service.param.query;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * Represents a JSON key-value condition for SQL WHERE clause.
 * The sqlExpression is generated by Dialect.jsonExtractText() and is safe from injection.
 */
@Data
@AllArgsConstructor
public class JsonCondition {

    /**
     * Dialect-generated SQL expression, e.g. "JSON_UNQUOTE(JSON_EXTRACT(task.extra, '$.category'))"
     */
    private String sqlExpression;

    /**
     * The comparison value (parameterized via #{}).
     */
    private String value;
}
