package com.alibaba.smart.framework.engine.service.param.query;

import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * Represents a JSON key IN (...) condition for SQL WHERE clause.
 * The sqlExpression is generated by Dialect.jsonExtractText() and is safe from injection.
 */
@Data
@AllArgsConstructor
public class JsonInCondition {

    /**
     * Dialect-generated SQL expression, e.g. "JSON_UNQUOTE(JSON_EXTRACT(task.extra, '$.category'))"
     */
    private String sqlExpression;

    /**
     * The list of values to match against.
     */
    private List<String> values;
}
