CREATE TABLE se_deployment_instance (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_definition_id varchar(255) NOT NULL,
  process_definition_version varchar(255),
  process_definition_type varchar(255),
  process_definition_code varchar(255),
  process_definition_name varchar(255),
  process_definition_desc varchar(255),
  process_definition_content text NOT NULL,
  deployment_user_id varchar(128) NOT NULL,
  deployment_status varchar(64) NOT NULL,
  logic_status varchar(64) NOT NULL,
  extension text,
  tenant_id varchar(64),
  PRIMARY KEY (id)
);

CREATE TABLE se_process_instance (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_definition_id_and_version varchar(128) NOT NULL,
  process_definition_type varchar(255),
  status varchar(64) NOT NULL,
  parent_process_instance_id bigint,
  parent_execution_instance_id bigint,
  start_user_id varchar(128),
  biz_unique_id varchar(255),
  reason varchar(255),
  comment varchar(255),
  title varchar(255),
  tag varchar(255),
  tenant_id varchar(64),
  PRIMARY KEY (id)
);

CREATE TABLE se_activity_instance (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint,
  process_definition_id_and_version varchar(255) NOT NULL,
  process_definition_activity_id varchar(64) NOT NULL,
  tenant_id varchar(64),
  PRIMARY KEY (id)
);

CREATE TABLE se_task_instance (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  process_definition_id_and_version varchar(128),
  process_definition_type varchar(255),
  activity_instance_id bigint NOT NULL,
  process_definition_activity_id varchar(255) NOT NULL,
  execution_instance_id bigint NOT NULL,
  claim_user_id varchar(255),
  title varchar(255),
  priority int DEFAULT 500,
  tag varchar(255),
  claim_time timestamp(6),
  complete_time timestamp(6),
  status varchar(255) NOT NULL,
  comment varchar(255),
  extension varchar(255),
  tenant_id varchar(64),
  PRIMARY KEY (id)
);

CREATE TABLE se_execution_instance (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  process_definition_id_and_version varchar(255) NOT NULL,
  process_definition_activity_id varchar(255) NOT NULL,
  activity_instance_id bigint NOT NULL,
  block_id bigint,
  active smallint NOT NULL,
  tenant_id varchar(64),
  PRIMARY KEY (id)
);

CREATE TABLE se_task_assignee_instance (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  task_instance_id bigint NOT NULL,
  assignee_id varchar(255) NOT NULL,
  assignee_type varchar(128) NOT NULL,
  tenant_id varchar(64),
  PRIMARY KEY (id)
);

CREATE TABLE se_variable_instance (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  execution_instance_id bigint,
  field_key varchar(128) NOT NULL,
  field_type varchar(128) NOT NULL,
  field_double_value decimal(65,30),
  field_long_value bigint,
  field_string_value varchar(4000),
  tenant_id varchar(64),
  PRIMARY KEY (id)
);