CREATE TABLE se_supervision_instance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  task_instance_id bigint NOT NULL,
  supervisor_user_id varchar(255) NOT NULL,
  supervision_reason varchar(500),
  supervision_type varchar(64) NOT NULL,
  status varchar(64) NOT NULL,
  close_time timestamp(6),
  tenant_id varchar(64)
);

CREATE INDEX idx_supervision_process_instance_id
  ON se_supervision_instance (process_instance_id);

CREATE INDEX idx_supervision_task_instance_id
  ON se_supervision_instance (task_instance_id);

CREATE INDEX idx_supervision_supervisor_user_id
  ON se_supervision_instance (supervisor_user_id);

CREATE INDEX idx_supervision_status
  ON se_supervision_instance (status);

CREATE INDEX idx_supervision_tenant_id
  ON se_supervision_instance (tenant_id);

COMMENT ON TABLE se_supervision_instance IS '督办记录表';
COMMENT ON COLUMN se_supervision_instance.supervision_type IS 'urge/track/remind';
COMMENT ON COLUMN se_supervision_instance.status IS 'active/closed';



CREATE TABLE se_notification_instance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  task_instance_id bigint,
  sender_user_id varchar(255) NOT NULL,
  receiver_user_id varchar(255) NOT NULL,
  notification_type varchar(64) NOT NULL,
  title varchar(255),
  content varchar(1000),
  read_status varchar(64) NOT NULL DEFAULT 'unread',
  read_time timestamp(6),
  tenant_id varchar(64)
);

CREATE INDEX idx_notification_process_instance_id
  ON se_notification_instance (process_instance_id);

CREATE INDEX idx_notification_task_instance_id
  ON se_notification_instance (task_instance_id);

CREATE INDEX idx_notification_sender_user_id
  ON se_notification_instance (sender_user_id);

CREATE INDEX idx_notification_receiver_user_id
  ON se_notification_instance (receiver_user_id);

CREATE INDEX idx_notification_read_status
  ON se_notification_instance (read_status);

CREATE INDEX idx_notification_tenant_id
  ON se_notification_instance (tenant_id);

COMMENT ON TABLE se_notification_instance IS '知会/抄送记录表';
COMMENT ON COLUMN se_notification_instance.notification_type IS 'cc/inform';
COMMENT ON COLUMN se_notification_instance.read_status IS 'unread/read';

CREATE TABLE se_assignee_operation_record (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  task_instance_id bigint NOT NULL,
  operation_type varchar(64) NOT NULL,
  operator_user_id varchar(255) NOT NULL,
  target_user_id varchar(255) NOT NULL,
  operation_reason varchar(500),
  tenant_id varchar(64)
);

CREATE INDEX idx_assignee_op_task_instance_id
  ON se_assignee_operation_record (task_instance_id);

CREATE INDEX idx_assignee_op_operation_type
  ON se_assignee_operation_record (operation_type);

CREATE INDEX idx_assignee_op_operator_user_id
  ON se_assignee_operation_record (operator_user_id);

CREATE INDEX idx_assignee_op_target_user_id
  ON se_assignee_operation_record (target_user_id);

CREATE INDEX idx_assignee_op_tenant_id
  ON se_assignee_operation_record (tenant_id);

COMMENT ON TABLE se_assignee_operation_record IS '加签/减签操作记录表';
COMMENT ON COLUMN se_assignee_operation_record.operation_type
  IS 'add_assignee/remove_assignee';




CREATE TABLE se_task_transfer_record (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  task_instance_id bigint NOT NULL,
  from_user_id varchar(255) NOT NULL,
  to_user_id varchar(255) NOT NULL,
  transfer_reason varchar(500),
  deadline timestamp(6),
  tenant_id varchar(64)
);

CREATE INDEX idx_task_transfer_task_instance_id
  ON se_task_transfer_record (task_instance_id);

CREATE INDEX idx_task_transfer_from_user_id
  ON se_task_transfer_record (from_user_id);

CREATE INDEX idx_task_transfer_to_user_id
  ON se_task_transfer_record (to_user_id);

CREATE INDEX idx_task_transfer_tenant_id
  ON se_task_transfer_record (tenant_id);

COMMENT ON TABLE se_task_transfer_record IS '任务移交记录表';


CREATE TABLE se_process_rollback_record (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  task_instance_id bigint NOT NULL,
  rollback_type varchar(64) NOT NULL,
  from_activity_id varchar(255) NOT NULL,
  to_activity_id varchar(255) NOT NULL,
  operator_user_id varchar(255) NOT NULL,
  rollback_reason varchar(500),
  tenant_id varchar(64)
);

CREATE INDEX idx_rollback_process_instance_id
  ON se_process_rollback_record (process_instance_id);

CREATE INDEX idx_rollback_task_instance_id
  ON se_process_rollback_record (task_instance_id);

CREATE INDEX idx_rollback_type
  ON se_process_rollback_record (rollback_type);

CREATE INDEX idx_rollback_operator_user_id
  ON se_process_rollback_record (operator_user_id);

CREATE INDEX idx_rollback_tenant_id
  ON se_process_rollback_record (tenant_id);

COMMENT ON TABLE se_process_rollback_record IS '流程回退记录表';
COMMENT ON COLUMN se_process_rollback_record.rollback_type
  IS 'previous/specific';
