-- Workflow enhancement database schema for PostgreSQL
-- Based on SmartEngine existing table structure design

-- ===========================================
-- Supervision instance table
-- ===========================================
CREATE TABLE se_supervision_instance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  task_instance_id bigint NOT NULL,
  supervisor_user_id varchar(255) NOT NULL,
  supervision_reason varchar(500),
  supervision_type varchar(64) NOT NULL,
  status varchar(64) NOT NULL,
  close_time timestamp(6),
  tenant_id varchar(64)
);

-- Composite index for findActiveByTaskId (high frequency query)
CREATE INDEX idx_supervision_task_status_tenant
  ON se_supervision_instance (task_instance_id, status, tenant_id);

-- Composite index for findBySupervisor
CREATE INDEX idx_supervision_supervisor_tenant
  ON se_supervision_instance (supervisor_user_id, tenant_id);

-- Single column index for cross-process queries
CREATE INDEX idx_supervision_process_instance_id
  ON se_supervision_instance (process_instance_id);

COMMENT ON TABLE se_supervision_instance IS 'Supervision instance table';
COMMENT ON COLUMN se_supervision_instance.supervision_type IS 'urge/track/remind';
COMMENT ON COLUMN se_supervision_instance.status IS 'active/closed';

-- ===========================================
-- Notification instance table
-- ===========================================
CREATE TABLE se_notification_instance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  task_instance_id bigint,
  sender_user_id varchar(255) NOT NULL,
  receiver_user_id varchar(255) NOT NULL,
  notification_type varchar(64) NOT NULL,
  title varchar(255),
  content varchar(1000),
  read_status varchar(64) NOT NULL DEFAULT 'unread',
  read_time timestamp(6),
  tenant_id varchar(64)
);

-- Composite index for findByReceiver (highest frequency query - user unread messages)
CREATE INDEX idx_notification_receiver_read_tenant
  ON se_notification_instance (receiver_user_id, read_status, tenant_id);

-- Composite index for findBySender
CREATE INDEX idx_notification_sender_tenant
  ON se_notification_instance (sender_user_id, tenant_id);

-- Single column indexes for cross-entity queries
CREATE INDEX idx_notification_process_instance_id
  ON se_notification_instance (process_instance_id);

CREATE INDEX idx_notification_task_instance_id
  ON se_notification_instance (task_instance_id);

COMMENT ON TABLE se_notification_instance IS 'Notification instance table';
COMMENT ON COLUMN se_notification_instance.notification_type IS 'cc/inform';
COMMENT ON COLUMN se_notification_instance.read_status IS 'unread/read';

-- ===========================================
-- Task transfer record table
-- ===========================================
CREATE TABLE se_task_transfer_record (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  task_instance_id bigint NOT NULL,
  process_instance_id bigint,
  from_user_id varchar(255) NOT NULL,
  to_user_id varchar(255) NOT NULL,
  transfer_reason varchar(500),
  deadline timestamp(6),
  tenant_id varchar(64)
);

-- Composite index for selectByTaskInstanceId
CREATE INDEX idx_task_transfer_task_tenant
  ON se_task_transfer_record (task_instance_id, tenant_id);

-- Single column indexes for user queries
CREATE INDEX idx_task_transfer_from_user_id
  ON se_task_transfer_record (from_user_id);

CREATE INDEX idx_task_transfer_to_user_id
  ON se_task_transfer_record (to_user_id);

COMMENT ON TABLE se_task_transfer_record IS 'Task transfer record table';

-- ===========================================
-- Assignee operation record table
-- ===========================================
CREATE TABLE se_assignee_operation_record (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  task_instance_id bigint NOT NULL,
  process_instance_id bigint,
  operation_type varchar(64) NOT NULL,
  operator_user_id varchar(255) NOT NULL,
  target_user_id varchar(255) NOT NULL,
  operation_reason varchar(500),
  tenant_id varchar(64)
);

-- Composite index for selectByTaskInstanceId
CREATE INDEX idx_assignee_op_task_tenant
  ON se_assignee_operation_record (task_instance_id, tenant_id);

-- Single column indexes for audit queries
CREATE INDEX idx_assignee_op_operation_type
  ON se_assignee_operation_record (operation_type);

CREATE INDEX idx_assignee_op_operator_user_id
  ON se_assignee_operation_record (operator_user_id);

CREATE INDEX idx_assignee_op_target_user_id
  ON se_assignee_operation_record (target_user_id);

COMMENT ON TABLE se_assignee_operation_record IS 'Assignee operation record table';
COMMENT ON COLUMN se_assignee_operation_record.operation_type IS 'add_assignee/remove_assignee';

-- ===========================================
-- Process rollback record table
-- ===========================================
CREATE TABLE se_process_rollback_record (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gmt_create timestamp(6) NOT NULL,
  gmt_modified timestamp(6) NOT NULL,
  process_instance_id bigint NOT NULL,
  task_instance_id bigint NOT NULL,
  rollback_type varchar(64) NOT NULL,
  from_activity_id varchar(255) NOT NULL,
  to_activity_id varchar(255) NOT NULL,
  operator_user_id varchar(255) NOT NULL,
  rollback_reason varchar(500),
  tenant_id varchar(64)
);

-- Composite index for selectByProcessInstanceId
CREATE INDEX idx_rollback_process_tenant
  ON se_process_rollback_record (process_instance_id, tenant_id);

-- Single column indexes for audit queries
CREATE INDEX idx_rollback_task_instance_id
  ON se_process_rollback_record (task_instance_id);

CREATE INDEX idx_rollback_type
  ON se_process_rollback_record (rollback_type);

CREATE INDEX idx_rollback_operator_user_id
  ON se_process_rollback_record (operator_user_id);

COMMENT ON TABLE se_process_rollback_record IS 'Process rollback record table';
COMMENT ON COLUMN se_process_rollback_record.rollback_type IS 'previous/specific';
